name = "LengthFreeStaticMatrices"
uuid = "aeef1611-66c2-4f82-a5cb-420906a81ec8"
authors = ["Brandon Flores <bsflores@wisc.edu>"]
version = "0.1.0"

[deps]
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[compat]
Aqua = "0.8"
StaticArrays = "1"
StaticArraysCore = "1"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "StaticArrays", "Test"]
